project_id = "nzenqhtautbitmbmgyjk"

[functions.get-participant-info]
verify_jwt = false

[functions.process-payment]
verify_jwt = false

[functions.check-in-participant]
verify_jwt = false

[functions.get-participant-card]
verify_jwt = false

[functions.resolve-tenant-secrets]
verify_jwt = false

[functions.update-tenant-secrets]
verify_jwt = true

[functions.line-webhook]
verify_jwt = false

[functions.unified-check-in]
verify_jwt = false